### PR TITLE
Fix #230 - render in dock

### LINKED ISSUE #230: Convert from Panel to Dock
Atom has added docks. It seems like a natural place for the terminal. http://blog.atom.io/2017/05/16/atom-1-17.html

-----------

# This is a community-driven plugin. We maintain it. Please provide PR.

### PR DESCRIPTION
**Pull request by akonwi**
### Pull request details

- [ ] This PR is a bug fix
- [x] This PR implements a new feature or introduces new behavior.

### Description of the change
Atom introduced [Docks](https://blog.atom.io/2017/05/16/atom-1-17.html) 2 years ago as a good place for some elements including terminals. This PR renders the terminal view within a tab inside the bottom dock.  Fixes #230

### Notes
Being in the dock provides consistency in atom UX.

### CODE REVIEW

**Comment by the-j0k3r** [comment]
@akonwi, thank you for reaching out with this contribution.

For my two cents here, this should be optional (off or on by default doesnt matter), straight replacing the bottom fixed position and removing the control buttons which some ppl use and are somewhat useful, especially the close button, because when you have many terminals open and want to close one or another you lose that granular control, the bottom close terminals button is all or nothing.

Edit:
Also its seems  the option in settings for the terminal height  is gone with these changes, like this we cant control the terminal height anymore either, for me as a user this is way less than ideal, because the terminal output is only easy to read when panel is at bottom, but I prefer to keep still editing space maximized by curtailing the terminal height which cant do anymore after this. 

Hopefully you will be receptive to a solution which will accommodate that user-base and long standing usage habits for a feature that once its in will likely never be touched again given the project status.

Thanks.

**Comment by akonwi** [comment]
That's good feedback. I'll update this to have it be a setting whether to use the dock or not. I might be able to make it so closing the terminal tab in the dock doesn't kill it like the current version does. 

Regarding the height, can't you resize the dock? I can add the preferred height setting and see if the dock respects that consistently.

**Comment by the-j0k3r** [comment]
>That's good feedback. I'll update this to have it be a setting whether to use the dock or not. I might be able to make it so closing the terminal tab in the dock doesn't kill it like.

Thanks =)

> Regarding the height, can't you resize the dock? 

Yes, but need to keep resizing after each terminal is open, where as before the default 300px (me at 200px height) it was a set and forget thing.

>I can add the preferred height setting and see if the dock respects that consistently.

Thanks, I could workaround using CSS, if the implementation naturally supported similar functions as before so that way no need to go under the hood.

And thanks again for this PR, to see individuals like yourself taking active interest in this project is a good thing for sure =)

**Comment by akonwi** [comment]
Gotcha. That makes sense. 

I'm happy to help. I just discovered this package a few weeks ago and it's very useful.

**Comment by akonwi** [comment]
I've pushed new changes to add a toggle for rendering in the dock.

**Comment by the-j0k3r** [comment]
Thank for this, give me some time to see how it works (hang in there =) ). In the meantime @ivankravets please review this.

**Comment by akonwi** [comment]
No rush. I'm also dogfooding it to catch stuff. Im going to see if I can get the auto open of terminal per file working correctly too

**Comment by the-j0k3r** [comment]
> No rush. I'm also dogfooding it to catch stuff. Im going to see if I can get the auto open of terminal per file working correctly too

:+1: :clinking_glasses: here's to success on all counts ;)

**Comment by the-j0k3r** [comment]
@akonwi finally had some time to actually test this better.

The implementation seems solid, there are a couple of issues (mabye 3 or 4) I see immediately, hopefully nothing big.

1. Render in bottom dock.

It only renders the terminal in bottom dock, I cant seem to be able to drag it anywhere else to left/top/either side.
While I agree that the most usable space for the terminal is at bottom and probably be an OK initial position, I would suggest making the dock render draggable to wherever the user wants (from its original position), thus making the dock version of the terminal 100% flexible.

The classic terminal (what Im calling it where its not the dock) is IMO OK where it is.

2. The position of the insert text icon, Im not sure really if its possible or not to move it further up, where it is ATM, feels like its wasting too much vertical space, between top of terminal dock and actual area where prompt is. See screenshot.

Capture

If at all possible move this into a position that is equally accessible and doesnt waste space, perhaps make the button smaller also? IDK ;)

3. This insert text icon is lost once the terminal has scrollback text to never come back again.
This maybe as designed IDK maybe if meant to be persistent then something else needs doing here.

generic

4. Opening more terminals while in dock (this breaks terminal in dock totally)

The best way to explain this is to show you.

generic

What you are seeing is that the following terminals dont output anything, mostly it doesnt. You need to go back and forth to each terminal to get something, Im not sure exactly why this is, but thats what I see locally.

Opening more terminals also seems to take some time to render the text. IDK if thats because my test environment is a VM or what...

## Unrelated issues.

There is perhaps another 2 issues (and apologies for bringing them up in  this manner) these issues **are not** related to your implementation of dock render, its up to you if you decide if you want or anything can be done about it in this ticket.

1. Im referring to the Close all button (see screenshot)

Capture

The associated ticket is #541

2. There is also still no scrollbar in the terminal, we only can scroll with mouse

Associated ticket #9 

I think both of those unrelated issues would make the terminal immediately more sane.

Finally and also offtopic please see https://discord.gg/EpdGSfH given recent developments we could discuss them in a more appropriate place, dont feel pressured to accept though.

I hope this feedback is easily understood, if not I will try to explain better.

Thanks and apologies for taking so long to get here.

**Comment by akonwi** [comment]
That's all good feedback. Keeping the thread here works better for me and this where I'd be more responsive aside from the Atom slack workspace.

1. I thought about making the dock movable and decided not to because I didn't want to deal with the conflicts that might introduce in terms of code compatibility. I can look into it and hopefully it's not too big of a change.

2. In trying to minimize the changes I didn't bother moving the insert text button. You are right, it's sort of obtrusive in its current position in the dock. I'd prefer to put it in the status bar with the other icons, while using the dock that is. Another option is to keep it in its current position but only show it when the mouse is in the terminal. What do you think?

3. My suggestions above would fix this

4. That's very odd. I use multiple terminal tabs with no issue. I'll investigate more.

As far as the other 2 issues. I can help with those too. Let's consider them as bonuses for this changeset and if I don't get to them, I'll create a separate PR after this.

**Comment by the-j0k3r** [comment]
>     2\. I'd prefer to put it in the status bar with the other icons

That would do it.

>     4\. That's very odd. I use multiple terminal tabs with no issue. I'll investigate more.

:+1: 



> As far as the other 2 issues. I can help with those too. Let's consider them as bonuses for this changeset and if I don't get to them, I'll create a separate PR after this.

Thats fine, I brought them up cause of the obvious relation. Lets hope though @ivankravets is paying attention to this.

> I'd be more responsive aside from the Atom slack workspace.

The Atom slack channel? Sure I have an account, if youre hanging around there it would be nice to chat.

**Comment by kale1d0code** [comment]
recent updates to this package caused this PR to break.
this is due to the addition of updateToolbarVisibility function within view.coffee

adding this fixes the problem
```
  updateToolbarVisibility: =>
    if !@shouldUseDock
```

**Comment by ivankravets** [comment]
@kaleidoc0de please make a new PR and we will archive this repo. No new changes more. Let's move to VSCode.

**Comment by the-j0k3r** [comment]
@akonwi @kaleidoc0de 

Please submit any pull requests to https://github.com/bus-stop/terminus

Ive worked on forking this project up to 2.10.0 and now its time to let this repo go into a deep slumber.

The project will live on and for such to happen please help out with code additions/changes/fixes to the new address at https://github.com/bus-stop/terminus.

Thanks you for all your support.

**Comment by srirambtechit** [comment]
https://atom.io/packages/x-terminal is a good alternative which provides docking feature

**Comment by the-j0k3r** [comment]
https://atom.io/packages/terminus also provides a way to move terminals into docks via DnD, + this PR is also open there.

**Pull request closed without merging**
