### PR TITLE
Switch from `pty.js` to `node.pty` with `node-pty-prebuilt`

### PR DESCRIPTION
**Pull request by the-j0k3r**
Supersedes  #551
Rebased #551 on master + added newer node-pty-prebuilt

* Based on node-pty-prebuilt 0.7.6 
* All Supported OS's are covered.

@ivankravets please review

@ashthespy @rustnnes

### CODE REVIEW

**Comment by the-j0k3r** [comment]
ping @ivankravets ;)

**Comment by ivankravets** [comment]
I'll review this PR when Atom releases a new update where we will need to rebuild binaries. Please ping me when Atom will switch to new Electron.

**Comment by the-j0k3r** [comment]
@ivankravets Atom just released v1.30.0 electron 2.0.5

**Comment by ivankravets** [comment]
Did they change node-module version?

**Comment by the-j0k3r** [comment]
I have no idea.

**Comment by ivankravets** [comment]
I've just checked, everything works well 👍

**Comment by the-j0k3r** [comment]
Excellent, so now what?

**Comment by the-j0k3r** [comment]
@ivankravets so we good for merge and release for 2.8.5?

**Comment by the-j0k3r** [comment]
@ivankravets ping reminder for merge

**Comment by Fred-Barclay** [comment]
@the-j0k3r I was about to use this my fork (it fixes https://github.com/Fred-Barclay/Termination/issues/86 and presumably #632 here). How should I credit you? I was planning on putting you as the author in git.
Cheers!
Fred

**Comment by Fred-Barclay** [comment]
Also @ivankravets this should fix #632 so I would definitely consider merging. :wink:

**Comment by the-j0k3r** [comment]
@Fred-Barclay node-pty 0.8.0 is out, however @daviwil hasnt synced node-pty-prebuilt since August, presumably busy with other projects and so on, it would be nice to get the newest prebuilt binaries in platformio-atom-ide-terminal even if at 0.7.6 it fixes a good deal of issues and is more reliable...

**Comment by ivankravets** [comment]
I see that `node-pty-prebuilt` is not active so much. Let's back to this issue if we will have again a problem with new Atom and terminal.

**Comment by the-j0k3r** [comment]
> Let's back to this issue if we will have again a problem with new Atom and terminal.

🤔

**Comment by ivankravets** [comment]
Thanks! Resolved in https://github.com/platformio/platformio-atom-ide-terminal/releases/tag/v2.9.0

Please re-test.

**Comment by ivankravets** [comment]
@the-j0k3r I would be thankful if you help with monitoring upcoming issues. If something will going wrong, I revert back latest changes.

Thanks!

**Pull request closed without merging**
