### PR TITLE
support platform-dependent 'shell' and 'shellArguments' options

### PR DESCRIPTION
**Pull request by NiklasRosenstein**
I use the same configuration for Atom on Windows and Mac OS, so being able to customize the `shell` and `shellArguments` option for both platforms is crucial to me. This pull request allows me to configure the terminal like this

```
core:
  windows:
    shellArguments: "/k C:\\Users\\niklas\\bin\\cmdinit.bat"
```

However, I do not know the Atom API well enough to know how to modify the visual Configuration Page of the package to reflect this change. Any hints are appreciated.

### CODE REVIEW

**Comment by NiklasRosenstein** [comment]
If this gets merged, eventually it would make sense to use `*` to match any platform besides the ones already configured instead of specifying `shell` and `shellArguments` on the same level. What I mean is currently you can do this

```
core:
  shell: "/bin/bash"
  windows:
    shell: "cmd.exe"
```

Whereas it would probably make more sense to use

```
core:
  "*":
    shell: "/bin/bash"
  windows:
    shell: "cmd.exe"
```

**Comment by NiklasRosenstein** [comment]
Confirmed that it's working fine on Windows.

**Comment by the-j0k3r** [comment]
@ivankravets this is unlikely to go anywhere. Close?

**Comment by the-j0k3r** [comment]
@NiklasRosenstein rebase on master and push

**Comment by the-j0k3r** [comment]
@NiklasRosenstein if you ever want to enhance this package see https://github.com/bus-stop/terminus now written in JavaScript

**Comment by the-j0k3r** [comment]
closing as no result after this long

**Pull request closed without merging**
