### PR TITLE
This should fix issue #523

### PR DESCRIPTION
**Pull request by mattpilott**

### CODE REVIEW

**Comment by rajatjindal** [comment]
I can confirm that this fixed issue for me

**Comment by the-j0k3r** [comment]
Read this https://github.com/platformio/platformio-atom-ide-terminal/issues/514#issuecomment-384241678

**Comment by the-j0k3r** [comment]
IT does fix the issue here also. for whatever that is worth.

The only problem is when doing ctr+c a `C^` character is printed in the current terminal line.
What has always worked for me is to use mouse select -> right click copy -> and right click paste 

Thx for effort and PR...

**Comment by ivankravets** [comment]
Thanks!

**Pull request merged**
