### PR TITLE
Christmas theme

### PR DESCRIPTION
**Pull request by Fred-Barclay**
Hey mates. Just wanted to send in a theme from my [fork](https://github.com/Fred-Barclay/Termination) as a "thank you!" for your great work! If you like it, merge it; if you hate it kick it out! :smile:

Cheers!
Fred

### CODE REVIEW

**Comment by ivankravets** [comment]
Hi Fred,

Do you use this theme?

**Comment by Fred-Barclay** [comment]
G'day @ivankravets

Yes, I do use it (almost) every day. 'Course now that it's January... :grin:

**Comment by ivankravets** [comment]
Please change from `Christmas` to `christmas` (to have a common style with other themes) and I'll merge.

Thanks!

**Comment by Fred-Barclay** [comment]
@ivankravets Do you want me to `git pull` all the changes since I opened the PR or just rename and let you handle the conflicts?
Cheers!

**Comment by ivankravets** [comment]
Ok, please delete current patch branch and make new PR.

**Comment by Fred-Barclay** [comment]
@ivankravets done! :smile: #132

**Pull request closed without merging**
