### PR TITLE
Updated default Windows shell to 64-bit Powershell if it exists.

### PR DESCRIPTION
**Pull request by stevenengler**
If running a 64-bit version of Windows, it should use the 64-bit version of PowerShell. This also removes the error message `Cannot load PSReadline module.  Console is running without PSReadline.` and allows you to run `bash` on Windows 10 from the PowerShell terminal. It shouldn't break compatibility with 32-bit computers.

I haven't explicitly rebuilt the package to test this since my computer isn't set up to build these, but the changes are very minimal so it should be easy to test. I have tested the added code just at the command line and the paths work out correctly.

### CODE REVIEW

**Comment by ivankravets** [comment]
Hi Steven,

Thanks a lot for PR. Do you use the latest Atom 1.15.0 x64 version? Also, please check that the latest version of this package is installed. We added pre-built PTY binaries for x64 a few weeks ago.

Thanks.

**Comment by stevenengler** [comment]
@ivankravets Thanks! I didn't realize there is a 64-bit build of Atom now, so I was on 1.15.0 32-bit. I've downloaded the 64-bit version and the default settings work properly, so this PR isn't needed. (Now to reinstall the packages that broke when updating to the 64-bit version...)

**Comment by DanielKlugGareis** [comment]
Hi, maybe yo can help me, I'm getting this error when I'm trying to use the console from Atom 1.18.0 x64.
Thanks!

**Comment by stevenengler** [comment]
Hi Daniel, did you switch from the 32-bit version of Atom or have you always been running the 64-bit version? Also can you post your operating system and the "Shell Override" setting for the package if it's not the default?

**Comment by DanielKlugGareis** [comment]
I've switched from 32-bit version, I uninstalled the 32-bit and then Installed the 64bit. I'm using windows10, and I'm using the default shell. Thank you very much!

**Comment by stevenengler** [comment]
Did you also uninstall the platformio-ide-terminal package? You need to uninstall and re-install the package after upgrading to 64-bit Atom. If that doesn't work, maybe try removing your `C:\Users\Name\.atom` folder (make a backup of it first since this will remove all your packages and settings) and reinstall the platformio-ide-terminal package.

**Pull request closed without merging**
