### PR TITLE
Add Solarized-Dark theme

### PR DESCRIPTION
**Pull request by jsg2021**

### CODE REVIEW

**Comment by ivankravets** [comment]
Thanks a lot! 👍

**Comment by maxnowack** [comment]
It seems that this wasn't released yet. Do you already have a plan when it will be available?

**Comment by ivankravets** [comment]
@maxnowack 2.2.0 is out! Please update.

**Comment by jsg2021** [comment]
The ansi colors aren't part of the theme... here's mine: (from the config.cson)

```
"platformio-ide-terminal":
    ansiColors:
      normal:
        black:
          red: 88
          green: 110
          blue: 117
          alpha: 1
        blue:
          red: 38
          green: 139
          blue: 210
          alpha: 1
        cyan:
          red: 42
          green: 161
          blue: 152
          alpha: 1
        green:
          red: 133
          green: 153
          blue: 1
          alpha: 1
        magenta:
          red: 211
          green: 54
          blue: 130
          alpha: 1
        red:
          red: 220
          green: 50
          blue: 47
          alpha: 1
        white:
          red: 101
          green: 123
          blue: 131
          alpha: 1
        yellow:
          red: 181
          green: 137
          blue: 1
          alpha: 1
      zBright:
        brightBlack:
          red: 101
          green: 123
          blue: 131
          alpha: 1
        brightBlue:
          red: 38
          green: 139
          blue: 210
          alpha: 1
        brightCyan:
          red: 42
          green: 161
          blue: 152
          alpha: 1
        brightGreen:
          red: 133
          green: 153
          blue: 1
          alpha: 1
        brightMagenta:
          red: 211
          green: 54
          blue: 130
          alpha: 1
        brightRed:
          red: 220
          green: 50
          blue: 47
          alpha: 1
        brightWhite:
          red: 147
          green: 161
          blue: 161
          alpha: 1
        brightYellow:
          red: 181
          green: 137
          blue: 1
          alpha: 1
    iconColors:
      blue:
        red: 38
        green: 139
        blue: 210
        alpha: 1
      cyan:
        red: 42
        green: 161
        blue: 152
        alpha: 1
      green:
        red: 133
        green: 153
        blue: 1
        alpha: 1
      magenta:
        red: 211
        green: 54
        blue: 130
        alpha: 1
      orange:
        red: 203
        green: 75
        blue: 22
        alpha: 1
      pink:
        red: 211
        green: 54
        blue: 130
        alpha: 1
      purple:
        red: 108
        green: 113
        blue: 196
        alpha: 1
      red:
        red: 220
        green: 50
        blue: 47
        alpha: 1
      yellow:
        red: 181
        green: 137
        blue: 1
        alpha: 1
```

**Pull request merged**
