### PR TITLE
Fix legacy prebuilds electron 3.x  macOS/Windows

### PR DESCRIPTION
**Pull request by the-j0k3r**
### Pull request details

- [X] This PR is a bug fix
- [ ] This PR implements a new feature or introduces new behavior.

### Notes

>Note: We will need to replace this version once again When Atom is actually using a supported build of electron 4.x - Somewhere in Atom 1.41.0 which is currently a nightly build.

Related #760 and https://github.com/oznu/node-pty-prebuilt-multiarch/pull/4

Tested Windows -> Working
Tested macOS -> Working
GNU Linux -> Not tested, all versions of electron were already supported and were working. :/

### CODE REVIEW

**Comment by the-j0k3r** [comment]
ping @ivankravets

**Comment by ivankravets** [comment]
Thanks!

**Comment by ivankravets** [comment]
Can we make a next release?

**Comment by the-j0k3r** [comment]
> Can we make a next release?

Besides 2.9.4? Not at this time, We come back to this type PR when Atom ships Elecron 4.0.0 or 4.0.4 versions.

Thx for your assistance with this 👍

**Pull request merged**
