### PR TITLE
Update package.json

### PR DESCRIPTION
**Pull request by fusion809**
Making the adjustment mentioned in issue 12 on [tensor5/atom](https://github.com/tensor5/arch-atom/issues/12).

### CODE REVIEW

**Comment by fusion809** [comment]
@ivankravets 

> 1. This solution will work only for the people that have C/C++ compiler installed.2
> 2. In platformio-ide-terminal we have pre-built pty's backends for the most popular OS/Archs.
> 3. The 2 bridges Win/Unix uses 2.0.5 NAN and obsolete WinPty (2013) year.
>    The original author doesn't support this package. This PR platformio/platformio-atom-ide-terminal#39 will not work at all.
> 
> Let's move discussion to platformio/platformio-atom-ide-terminal#39
> 
> I'll try to port existing code to the latest NAN and WinPty and prepare a few "after-gyp"s for the popular OS and will ask you to try it

OK, I shall await any attempted fixes you come up with. I can try them out on a few other Linux distros via VirtualBox VMs, including:
- CentOS 7
- Debian 8
- Fedora 23
- Gentoo Linux
- Linux Mint 17.3
- Mageia 5
- openSUSE Leap 42.1 & Tumbleweed
- Ubuntu 16.04

too if you would like me to.

**Comment by ivankravets** [comment]
See my answer here https://github.com/chjj/pty.js/pull/159#issuecomment-223926975

**Comment by ivankravets** [comment]
@fusion809 why do you need "yet another fork"?

**Comment by fusion809** [comment]
Not much of a reason why, I just created it because I wanted to release a version of the package with the `linux` theme ASAP. Oh and that reminds me I'm gonna go offer a solution to one of your issues on this repo.

**Comment by ivankravets** [comment]
1. I propose to support the one fork and merge it to original @jeremyramin's when he will be back
2. "I wanted to release a version of the package with the linux theme ASAP.". Do you have the users that need it?

**Comment by ivankravets** [comment]
@fusion809 I propose you to remove your fork of this PlatformIO IDE Terminal package. Then please make clean PR and I'll merge it and make release.

Thanks.

**Comment by ivankravets** [comment]
PlatformIO IDE Terminal 2.1.0 is out!

**Pull request closed without merging**
