### PR TITLE
Fullscreen command

### PR DESCRIPTION
**Pull request by markoradak**
Adds 'platformio-ide-terminal:fullscreen' command.

### CODE REVIEW

**Comment by ivankravets** [comment]
Thank a lot!

**Comment by markoradak** [comment]
No problem :) I didn't realize terminal-plus was no longer maintained, at the time of submission. I would have looked for an alternative otherwise.

**Comment by ivankravets** [comment]
Does it work for you? I've justed merged changes and "menu item" with maximize doesn't work for me.

**Comment by markoradak** [comment]
Yes, just double checked it... Here's the result:

platformio-ide-terminal

**Comment by ivankravets** [comment]
Cool! 👍 

P.S: What do you use to record GIF 😊 ?

**Comment by ivankravets** [comment]
Does it work for you via `Packages > platformio-ide-terminal > Toggle Fullscreen`?

**Comment by markoradak** [comment]
Oh, you're right actually. I just noticed I accidentally left it as `terminal-plus:fullscreen`. I just updated it within my fork, but you've already merged PR. Should I resubmit it, or..?

Sorry once again... I guess staying up all night doesn't do good for me 😆

**Comment by markoradak** [comment]
I just tried it again, after removing `terminal-plus` package - it works as expected. Same with `packages > platformio-ide-terminal > Toggle Fullscreen`

**Comment by markoradak** [comment]
As for gif - **Giphy Capture** is the name of the app 😊

**Comment by ivankravets** [comment]
Thanks, fixed.

P.S: Thanks for the Giphy Capture 👍

**Comment by markoradak** [comment]
Great! Once again - sorry for the trouble.

**Comment by ivankravets** [comment]
If you have any ideas how to resolve one of these issues, don't hesitate to make PR.
- https://github.com/platformio/platformio-atom-ide-terminal/issues
- https://github.com/jeremyramin/terminal-plus/issues

Thanks!

**Comment by markoradak** [comment]
Sure thing! I'll take a look when I catch some time :)

**Comment by joshmedeski** [comment]
Do you guys have an ETA when this will be live for the rest of us?

**Comment by ivankravets** [comment]
@joshmedeski Done! Please upgrade to 2.0.10 release.

**Pull request merged**
