### PR TITLE
update to node-pty-prebuilt-multiarch

### PR DESCRIPTION
**Pull request by the-j0k3r**
its publishing binaries for all platforms since node-pty 0.8.1

https://github.com/oznu/node-pty-prebuilt-multiarch

### Pull request details

- [x] This PR is a bug fix
- [ ] This PR implements a new feature or introduces new behavior.

### Notes

Using https://github.com/oznu/node-pty-prebuilt-multiarch should fix all our woes, if not, I have no other solution at this time.

### CODE REVIEW

**Comment by the-j0k3r** [comment]
@ivankravets this should get things working smootly again, tested fully working, please confirm

**Comment by ivankravets** [comment]
Thank you so much! 😊

**Comment by the-j0k3r** [comment]
Well its a hit and miss we already have issue reports https://github.com/platformio/platformio-atom-ide-terminal/issues/755

No ideas here, Ill see if thers other alternatives.

**Comment by the-j0k3r** [comment]
fix up https://github.com/platformio/platformio-atom-ide-terminal/pull/757
sorry.

**Pull request merged**
